### ISSUE TITLE
Transform Base class is not pickable

### ISSUE THREAD

**Issue by reox** [SimpleITK/SimpleITK#1112]
As discussed here: https://discourse.itk.org/t/how-to-pickle-simpleitk-transforms/901/12

The Transform base class is not pickleable in 2.0.0rc1:

```
>>> import SimpleITK as sitk
>>> import pickle
>>> pickle.loads(pickle.dumps(sitk.Transform()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reox/.local/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 4562, in __init__
    _SimpleITK.Transform_swiginit(self, _SimpleITK.new_Transform(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_Transform'.
  Possible C/C++ prototypes are:
    itk::simple::Transform::Transform()
    itk::simple::Transform::Transform(itk::TransformBase *)
    itk::simple::Transform::Transform(unsigned int,itk::simple::TransformEnum)
    itk::simple::Transform::Transform(itk::simple::Image &,itk::simple::TransformEnum)
    itk::simple::Transform::Transform(itk::simple::Transform const &)
```

**Comment by blowekamp** [comment]
Pickling also does not work with composite transforms represented as sitk::Transform.

**Comment by reox** [comment]
Additional info: It also does not work if the transformation is returned from `ImageRegistrationMethod`. In that case also `Transform` is used and not the actual type.
Workaround: After running ImageRegistrationMethod cast the Transform into the correct form.

**Comment by reox** [comment]
I wrote this little test script to check which transformations work and which not:
```
import SimpleITK as sitk
import pickle
import sys

transforms = {
    'AffineTransform': (3,),
    'BSplineTransform': (3, 3),
    'DisplacementFieldTransform': (3,),
    'Euler2DTransform': (),
    'Euler3DTransform': (),
    'ScaleSkewVersor3DTransform': (),
    'ScaleTransform': (3,),
    'ScaleVersor3DTransform': (),
    'Similarity2DTransform': (),
    'Similarity3DTransform': (),
    'Transform': (),
    'TranslationTransform': (3, ),
    'VersorRigid3DTransform': (),
    'VersorTransform': ()
}

print("System Version: ", sys.version)
print('SimpleITK Version:   ', sitk.Version_VersionString())
print('          Build Date:', sitk.Version_BuildDate())
print('ITK Version:         ', sitk.Version_ITKVersionString())
print()

for k, v in transforms.items():
    t = getattr(sitk, k)(*v)
    print('{:30}'.format(k), end=" ")
    try:
        pickle.loads(pickle.dumps(t))
    except NotImplementedError:
        print("DOES NOT WORK")
    else:
        print("works")
```

for me it outputs:
```
AffineTransform                works
BSplineTransform               works
DisplacementFieldTransform     works
Euler2DTransform               DOES NOT WORK
Euler3DTransform               DOES NOT WORK
ScaleSkewVersor3DTransform     DOES NOT WORK
ScaleTransform                 works
ScaleVersor3DTransform         DOES NOT WORK
Similarity2DTransform          works
Similarity3DTransform          DOES NOT WORK
Transform                      DOES NOT WORK
TranslationTransform           works
VersorRigid3DTransform         DOES NOT WORK
VersorTransform                DOES NOT WORK
```

**Comment by blowekamp** [comment]
That looks great:

This is the current testing file:
https://github.com/SimpleITK/SimpleITK/blob/master/Testing/Unit/Python/sitkTransformTests.py

PR's to improve testing are welcomed! (But will not be merged until the bug is fixed.)
