### ISSUE TITLE
tobytes in cupy.core.core.ndarray is missing

### ISSUE THREAD

**Issue by kryztoval** [SimpleITK/SimpleITK#1152]
```
import cupy

nd_array = cupy.random.randint(0,256,8)
print(nd_array)
byte_array = nd_array.tobytes()
print(byte_array)
```

```
[152 188 211 223 201 255 251  49]
Traceback (most recent call last):
  File "tobytes_test.py", line 5, in <module>
    byte_array = nd_array.tobytes()
AttributeError: 'cupy.core.core.ndarray' object has no attribute 'tobytes'
```

however it works if the ndarray is gotten first.
nd_array.get().tobytes()

However the documentation clearly states that ndarray has a property called tobytes,

**Comment by blowekamp** [comment]
This does appear related to the recent change here: https://github.com/SimpleITK/SimpleITK/pull/1151

However, this issue appears to be requesting fixes for cupy.

**Comment by kryztoval** [comment]
```
import cupy

nd_array = cupy.random.randint(0,256,32,'<u1')
nd_new_array = cupy.ndarray(32, 'uint8')
nd_new_array.set(nd_array.get())
print(nd_array.get())
print(nd_new_array.tobytes())
```

```
[  2 128  71  64  36  57 143  21 108 215 166 220  10  13 187  17 170 163
  33 177  90  36 154 156 212 214  71 176 160 105 241 125]
Traceback (most recent call last):
  File "tobytes_test.py", line 7, in <module>
    print(nd_new_array.tobytes())
AttributeError: 'cupy.core.core.ndarray' object has no attribute 'tobytes'
```
It seems the method _tobytes_ is only missing if the ndarray is on the gpu
This behaviour is not obvious since other functions do work and exist whether it is on the GPU or in CPU memory.

**Comment by kryztoval** [comment]
Oh wow, did I add this issue in the wrong repository? My bad, moving this to cupy.
