### ISSUE TITLE
SimpleITK 2.1.0 No longer able to read nii.gz file

### ISSUE THREAD

**Issue by kleingeo** [SimpleITK/SimpleITK#1452]
I upgrade to sitk 2.1.0 to use torchio, and I am now getting errors trying to open a file. This problem did not exist with sitk 2.0.2 which I was using previously. 

Both environments (sitk 2.1.0 and sitk 2.0.2) were using ITK 5.2.0.post2

```python

sitk.ReadImage(self.base_folder + '/' + spine_sample)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "D:\Miniconda3\envs\main_env_2\lib\site-packages\SimpleITK\extra.py", line 346, in ReadImage
    return reader.Execute()
  File "D:\Miniconda3\envs\main_env_2\lib\site-packages\SimpleITK\SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk-build\ITK\Modules\IO\NIFTI\src\itkNiftiImageIO.cxx:1980:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

```

**Comment by zivy** [comment]
Hello @kleingeo,

This is an issue with the image, ITK now enforces a requirement it previously didn't. Please see issue #1433.

**Comment by kleingeo** [comment]
So does this just mean that SimpleITK can no longer read the files properly? This seems like a massive issue.....

**Comment by zivy** [comment]
Hello @kleingeo,

No, this doesn't mean that SimpleITK can no longer read these files. 

The issue was introduced in ITK and is resolved in ITK, see InsightSoftwareConsortium/ITK#1868 which was referenced in the SimpleITK issue pointed to above and the associated discussion  InsightSoftwareConsortium/ITK#2674 and [this PR](https://github.com/InsightSoftwareConsortium/ITK/commit/6278c4171f697649da5b3136214cfbb8e37aab00) which addresses it. Should be out in ITK v.5.3.0 and shortly thereafter in SimpleITK.

**Comment by blowekamp** [comment]
When PR#1450 is merged into SimpleITK master, the next nightly build of SimpleITK will contain the referenced fix from ITK. This will mean that SimpleITK 2.1.x will contain this issue, but previous and later releases will not have it.
