### ISSUE TITLE
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105: sitk::ERROR: Unable to determine ImageIO reader

### ISSUE THREAD

**Issue by huanqingxu** [SimpleITK/SimpleITK#1506]
[PosixPath('/media/lab549/CE56C94660FE3E83/semantic segmentation_xhq/code_xhq/CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT'), PosixPath('/media/lab549/CE56C94660FE3E83/semantic segmentation_xhq/code_xhq/CoraNet-master/dataset/Pancreas-CT/data/metadata.csv')]
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5F.c line 370 in itk_H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 830 in itk_H5F__is_hdf5(): unable to locate file signature
    major: File accessibilty
    minor: Not an HDF5 file
  #002: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 126 in itk_H5FD_locate_signature(): unable to read file signature
    major: Low-level I/O
    minor: Unable to initialize object
  #003: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 205 in itk_H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #004: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 725 in H5FD_sec2_read(): file read failed: time = Sat Nov  6 20:59:42 2021
, filename = '/media/lab549/CE56C94660FE3E83/semantic segmentation_xhq/code_xhq/CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT/PANCREAS_0001/11-24-2015-PANCREAS0001-Pancreas-18957/Pancreas-99667', file descriptor = 4, errno = 21, error message = 'Is a directory', buf = 0x7ffca8f6b358, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Read failed
Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/media/lab549/CE56C94660FE3E83/semantic segmentation_xhq/code_xhq/CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT/PANCREAS_0001/11-24-2015-PANCREAS0001-Pancreas-18957/Pancreas-99667"
Traceback (most recent call last):
  File "pancreas_preprocess.py", line 76, in process_case
    slice, spacing, affine_pre = io_.read_nii(slice_path)
  File "/media/lab549/CE56C94660FE3E83/semantic segmentation_xhq/code_xhq/CoraNet-master/preprocess/io_.py", line 78, in read_nii
    img = sitk.ReadImage(path)
  File "/home/lab549/anaconda3/envs/transunet/lib/python3.7/site-packages/SimpleITK/extra.py", line 346, in ReadImage
    return reader.Execute()
  File "/home/lab549/anaconda3/envs/transunet/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/media/lab549/CE56C94660FE3E83/semantic segmentation_xhq/code_xhq/CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT/PANCREAS_0001/11-24-2015-PANCREAS0001-Pancreas-18957/Pancreas-99667"
total time : 0.0024590333302815753 min

**Comment by gdevenyi** [comment]
The error is simpleitk doesn't know what your image is. L

What is it?

**Comment by zivy** [comment]
Hello @huanqingxu,

Simply posting the error message from an exception will not allow us to help you beyond what the error message states:

"sitk::ERROR: Unable to determine ImageIO reader for "/media/lab549/CE56C94660FE3E83/semantic segmentation_xhq/code_xhq/CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT/PANCREAS_0001/11-24-2015-PANCREAS0001-Pancreas-18957/Pancreas-99667"

SimpleITK is not able to automatically identify the file format and thus cannot read this file. For additional information on supported file types please see [documentation on read-the-docs](https://simpleitk.readthedocs.io/en/master/IO.html).
