### ISSUE TITLE
Install on IpadOS v16.6

### ISSUE THREAD

**Issue by Nicolaeus** [SimpleITK/SimpleITK#2022]
**Describe the bug**
When I install with pip I have this issue :

Defaulting to user installation because normal site-packages is not writeable
Collecting SimpleITK
  Using cached SimpleITK-2.1.1.2.tar.gz (2.0 MB)
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running dist_info
      creating /private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK.egg-info
      writing /private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK.egg-info/PKG-INFO
      writing dependency_links to /private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK.egg-info/dependency_links.txt
      writing top-level names to /private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK.egg-info/top_level.txt
      writing manifest file '/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK.egg-info/SOURCES.txt'
      listing git files failed - pretending there aren't any
      reading manifest file '/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'SimpleITK/.ExternalData'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      writing manifest file '/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK.egg-info/SOURCES.txt'
      creating '/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-modern-metadata-55jiw8v6/SimpleITK-2.1.1.2.dist-info'
      Traceback (most recent call last):
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/scikit_build-0.11.2.dev202+g9cc7823-py3.11.egg/skbuild/setuptools_wrap.py", line 507, in setup
          return setuptools.setup(**kw)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 101, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/scikit_build-0.11.2.dev202+g9cc7823-py3.11.egg/skbuild/command/bdist_wheel.py", line 54, in finalize_options
          if sys.platform == 'darwin' and self.plat_name is None and self.distribution.has_ext_modules():
             ^^^
      NameError: name 'sys' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**To Reproduce**

1. Operating system, version, and architecture
 - OS: [IpadOs v16.6 ]
 - Architecture: [Ipad gen6]
2. Programming language, and version [Python 3.11, ].
3. Version of SimpleITK : no version.
4. How was SimpleITK installed?
 - binary distribution : pip install SimpleITK in app Carnets

**Expected behavior**

Fix it ^^

**Images**
If applicable, include a minimal sized sample input and output image. Or SimpleITK commands to synthetically generate
an input.

**Additional context**

If you can fix it, it will be cool!
Thank you !!
Nicolaeus

**Comment by blowekamp** [comment]
The error message comes from scikit-build. And the path includes "scikit_build-0.11.2.dev202+g9cc7823-py3.11.egg"  which I will presume is the version of the tool. I suggest update scikit-build to a recent release.

**Comment by Nicolaeus** [comment]
I test to upgrade but I have this now about scikit-learn : 

error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Partial import of sklearn during the build process.
      clang: command not found
      Traceback (most recent call last):
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'clang' failed with exit code 127
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 632, in <module>
        File "<string>", line 626, in setup_package
        File "<string>", line 554, in configure_extension_modules
        File "/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-install-452fswso/scikit-learn_654e8b0618a14185b79e74b4848aab21/sklearn/_build_utils/__init__.py", line 46, in cythonize_extensions
          basic_check_build()
        File "/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-install-452fswso/scikit-learn_654e8b0618a14185b79e74b4848aab21/sklearn/_build_utils/pre_build_helpers.py", line 73, in basic_check_build
          compile_test_program(code)
        File "/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-install-452fswso/scikit-learn_654e8b0618a14185b79e74b4848aab21/sklearn/_build_utils/pre_build_helpers.py", line 31, in compile_test_program
          ccompiler.compile(
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'clang' failed with exit code 127
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by zivy** [comment]
Closing due to long time since question was asked. If still relevant please feel free to reopen.
