### ISSUE TITLE
Python: trying to create Image from unsupported array data-type format gives cryptic error

### ISSUE THREAD

**Issue by gdevenyi** [SimpleITK/SimpleITK#238]
My student was (for some reason) using float16 numpy arrays for a calculation and then trying to create/save an image from SimpleITK, it gives this cryptic error:
```python
Traceback (most recent call last):
  File "./potential_maps3.10.py", line 421, in <module>
    awolmrf.get_potential_maps()
  File "./potential_maps3.10.py", line 249, in get_potential_maps
    singleton_image = sitk.GetImageFromArray(singleton_map)
  File "/project/m/mchakrav/quarantine/SimpleITK/1.0/build/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 3432, in GetImageFromArray
    img = Image( z.shape[::-1], id )
  File "/project/m/mchakrav/quarantine/SimpleITK/1.0/build/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 3683, in __init__
    this = _SimpleITK.new_Image(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_Image'.
  Possible C/C++ prototypes are:
    itk::simple::Image::Image()
    itk::simple::Image::Image(itk::simple::Image const &)
    itk::simple::Image::Image(unsigned int,unsigned int,itk::simple::PixelIDValueEnum)
    itk::simple::Image::Image(unsigned int,unsigned int,unsigned int,itk::simple::PixelIDValueEnum)
    itk::simple::Image::Image(std::vector< unsigned int,std::allocator< unsigned int > > const &,itk::simple::PixelIDValueEnum,unsigned int)
```

Would've been helpful to complain about the datatype being passed.

**Comment by blowekamp** [comment]
Thank you for reporting this issue. Can you please provide a small snippet of code to reproduce the error message?

**Comment by gdevenyi** [comment]
```python
import SimpleITK as sitk
import numpy as np

numpy_array = np.zeros((3,3,3), np.float16)
simpleitk_image = sitk.GetImageFromArray(numpy_array)
```

```python
Traceback (most recent call last):
  File "float16_error.py", line 5, in <module>
    simpleitk_image = sitk.GetImageFromArray(numpy_array)
  File "/opt/quarantine/anaconda/4.3.0-python2.7/build/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 351, in GetImageFromArray
    img = Image( z.shape[::-1], id )
  File "/opt/quarantine/anaconda/4.3.0-python2.7/build/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 3741, in __init__
    this = _SimpleITK.new_Image(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_Image'.
  Possible C/C++ prototypes are:
    itk::simple::Image::Image()
    itk::simple::Image::Image(itk::simple::Image const &)
    itk::simple::Image::Image(unsigned int,unsigned int,itk::simple::PixelIDValueEnum)
    itk::simple::Image::Image(unsigned int,unsigned int,unsigned int,itk::simple::PixelIDValueEnum)
    itk::simple::Image::Image(std::vector< unsigned int,std::allocator< unsigned int > > const &,itk::simple::PixelIDValueEnum,unsigned int)
```

**Comment by blowekamp** [comment]
Thank you fro including the test case.
