### ISSUE TITLE
Python.Test.ImageIndexing  fails with Python 3.7

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#552]
```
2: Test command: /tmp/SimpleITK-build-cp37-cp37m/Testing/Installation/PythonVirtualenv/bin/python "/tmp/SimpleITK/Testing/Unit/Python/ImageIndexingTest.py"
2: Test timeout computed to be: 1500
2: E...
2: ======================================================================
2: ERROR: test_2d (__main__.TestImageIndexingInterface)
2: testing __getitem__ for 2D image
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/tmp/SimpleITK-build-cp37-cp37m/Testing/Installation/PythonVirtualenv/lib/python3.7/site-packages/SimpleITK-1.1.0rc1-py3.7-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 4450, in __iter__
2:     raise StopIteration
2: StopIteration
2: 
2: The above exception was the direct cause of the following exception:
2: 
2: Traceback (most recent call last):
2:   File "/tmp/SimpleITK/Testing/Unit/Python/ImageIndexingTest.py", line 87, in test_2d
2:     self.assertImageNDArrayEquals(img[-4:-1:-2,-2:-1:1],nda[-2:-1:1,-4:-1:-2])
2:   File "/tmp/SimpleITK/Testing/Unit/Python/ImageIndexingTest.py", line 35, in assertImageNDArrayEquals
2:     for p,n in zip(img, nda.flat):
2: RuntimeError: generator raised StopIteration
2: 
2: ----------------------------------------------------------------------
2: Ran 4 tests in 0.068s
2: 
2: FAILED (errors=1)
```
This appears to be related to PEP 479:
https://www.python.org/dev/peps/pep-0479/

**Comment by blowekamp** [comment]
PR #554 fixes this issue.
